jobs:
- job:  Windows_py_GPU_Wheels
  pool: Win-GPU
  variables:
    buildDirectory: '$(Build.SourcesDirectory)\build'
    CUDA_VERSION: '9.1'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
    - task: CondaEnvironment@1
      inputs:
        createCustomEnvironment: true
        environmentName: 'py$(python.version)'
        packageSpecs: 'python=$(python.version)'
        cleanEnvironment: true

    - task: PowerShell@1
      displayName: 'Set CUDA path'
      inputs:
        scriptName: 'tools/ci_build/github/windows/set_cuda_path.ps1'
        arguments: '-CudaMsbuildPath C:\local\cudaMsbuildIntegration-9.1.85-windows10-x64-0 -CudaVersion $(CUDA_VERSION)'

    - task: BatchScript@1
      displayName: 'Setup VS2017 env vars'
      inputs:
        filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat'
        arguments: 'amd64 -vcvars_ver=14.11'
        modifyEnvironment: true

    - task: BatchScript@1
      displayName: 'Run build script'
      inputs:
        filename: 'build.bat'
        arguments: ' --use_cuda --cuda_home="C:\local\cuda-9.1.85-windows10-x64-0"
      --cudnn_home="C:\local\cudnn-9.1-windows10-x64-v7.1\cuda" --build_dir $(buildDirectory) --config Release --use_openmp --build_wheel'
        workingFolder: "$(Build.SourcesDirectory)"

    - task: CopyFiles@2
      displayName: 'Copy Python Wheel to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(buildDirectory)'
        Contents: '**\dist\onnxruntime_gpu-*.whl'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: ONNXRuntime python wheel'
      inputs:
        ArtifactName: onnxruntime_gpu

    - task: CmdLine@1
      displayName: 'Deactivating Conda Environment'
      inputs:
        filename: deactivate
      continueOnError: true
      condition: always()

    - template: templates/clean-agent-build-directory-step.yml

